
CREATE TABLE user2 (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  name varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (id)
);