DROP TABLE IF EXISTS user2;

CREATE TABLE user2 (
	id BIGINT ( 20 ) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR ( 64 ) COLLATE utf8mb4_bin DEFAULT NULL,
	updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	temp_name VARCHAR ( 64 ) COMMENT '中间状态的用户名',
	PRIMARY KEY ( id )
);

INSERT INTO user2 ( NAME ) VALUES( 'user2' );